global:
  resolve_timeout: 5m

route:
  group_by: [alertname, job]
  group_wait: 20s
  group_interval: 60s
  repeat_interval: 110s
  receiver: 'web.hook'
  routes:
  - group_by: [job, severity]
    group_wait: 10s
    group_interval: 20s
    repeat_interval: 70s
    receiver: 'web.hook'
    match_re:
      severity: critical

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:8081/'
    send_resolved: true
